server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/item/ {
        proxy_pass http://item-service:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/claim/ {
        proxy_pass http://claim-recovery-service:8002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/notif/ {
        proxy_pass http://notification-service:8003/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
